import Head from 'next/head'
import React from 'react'
import ActionAreaCard from '../components/Menu/ActionAreaCard'
import Main from '../components/Menu/Main'
import NavBar from '../components/Menu/NavBar'
import CardMyReipes from '../components/SectionMyRecipes/CardMyRecipes'
import style from '../styles/index.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />

      </Head>
      <header>
        <NavBar></NavBar>
        <Main />
      </header>
      <section>
        <CardMyReipes />
      </section>
    </div>
  )
}
